version: '3.8'

services:
  flask-api:
    build: .
    image: ocr-receipt-v1
    container_name: ocr-container
    ports:
      - "${PORT_OCR}:8000"
    env_file:
      - .env
    volumes:
      - "${UPLOAD_FOLDER}:/app/uploads"
